### ISSUE TITLE
Check for desired options in raw data

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.data.preparation#11]
It would be advantageous to check if the desired options (scenarios, sectors, etc.) exist in the raw input data files (AR data, scenario data, etc.) before running the full process.

Supersedes https://github.com/RMI-PACTA/pacta.data.preparation/issues/63

**Comment by cjyetman** [comment]
After looking into this a bit, I'm not sure this is entirely feasible/desirable. Hypothetically, at the beginning of this script just after all the options are set we could verify that the set options, e.g. list of desired sectors, are available in the appropriate datasets, but that would imply loading those datasets to be able to check, and since memory management in this script is a *big deal*, I fear the cost might outweigh the benefit. @jdhoffa?

**Comment by cjyetman** [comment]
I agree that a possibly suitable alternative would be to add checking for crucial input in functions in pacta.data.preparation. Issue opened here https://github.com/RMI-PACTA/pacta.data.preparation/issues/327

**Comment by jdhoffa** [comment]
Closing in favour of https://github.com/RMI-PACTA/pacta.data.preparation/issues/327
