### ISSUE TITLE
Determine what the `additional_year` param is used for

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.data.preparation#33]
Currently, it adds the (specific) years `2030` and `2040` for analysis in scenario preparation. 

Having two hard-coded years seems potentially not future-proof, and it is unclear what exactly these added years are required for. 

Relates to #31

**Comment by cjyetman** [comment]
@jacobvjk do you know if 2040 was required for stress testing?

**Comment by cjyetman** [comment]
marking as `priority` because this is major tech debt that will only get harder to figure out as time passes

**Comment by jdhoffa** [comment]
Added context (that we are probably already aware of):
From a (very) recent conversation with Kuba, stress testing is likely not going to ever be added back into PACTA, so if this is a stress testing artifact it is likely safe to remove.

**Comment by jacobvjk** [comment]
This was never used for stress testing. I am not aware of the initial use case for these years

**Comment by AlexAxthelm** [comment]
So it appears that `additional_year` was included in the first code commit of `PACTA_analysis`, which means it's ancient enough that it came from the before-GitHub times

https://github.com/RMI-PACTA/PACTA_analysis/blob/bcd05578f3def1bf13caf894eb9ace412f7d8f98/0_global_functions.R#L49

But looking at an [org-level search](https://github.com/search?q=org%3ARMI-PACTA+additional_year&type=code), I'm not seeing it used as an argument in any of our active repos

I'm inclined to mark this one as a piece of cruft that's been kept because nobody knew we could let it go, that happened to get picked up again as part of TDM. Since we've now explicitly called out the TDM years in #31 / #34, I suggest we remove `additional_year`, unless anyone can find a compelling reason to keep it in.

**Comment by jdhoffa** [comment]
I am in favour of removing it as well!

**Comment by cjyetman** [comment]
Also called `Years.Additional` in [some places](https://github.com/search?q=org%3ARMI-PACTA+Years.Additional&type=code), but as far as I've found, only ever described as something like...

https://github.com/RMI-PACTA/data_preparation/blob/d4d3c56a61dedf8ac4a62bfc3897a3275864d6a3/vignettes/YAML-file.Rmd#L61
> **Years.Additional**: list of positive four digit integer values, e.g `- 2030`; determines which additional years should be included in the output data beyond the initial period of `Years.Startyear` through `Years.Startyear + Years.Horizon`; must exist in the data or will cause an error; NOTE: in some cases `start_year + 10` is hard-coded into the process, so that year may show up in the result even if it is not included in this option

**Comment by AlexAxthelm** [comment]
Increasingly convinced that that we can pull it.

**Comment by cjyetman** [comment]
just some more color...

@jdhoffa and I just discussed this offline. `Years.Additional` may also have been used, maybe even originated, in the old data.prep to determine which scenario data was needed/used to interpolate scenario data across years. But scenario preparation is all done by pacta.scenario.preparation and @jdhoffa verified that this `additional_year` variable is irrelevant there.

So we have 3 potential uses for these additional year:
- scenario preparation/interpolation
- calculation of TDM (because it has a longer horizon than PACTA)
- stress testing (because it may have/had a longer horizon than PACTA)

In all three cases, we've determined that `additional_year` is not necessary anymore.
