### ISSUE TITLE
Consider move all scraping functions to the start of the workflow script

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.data.preparation#50]
The scraping functionality (for currencies and index_regions) is pretty brittle, and often fails. 
It would be good to attempt this right at the beginning of the script, so we can know very quickly if it failed, and try to re-run. 

As it is, some of the scraping (the index_regions) occurs AFTER we pull financial data, which is also a lengthy tasks, so it takes a while to know if the workflow fails

**Comment by cjyetman** [comment]
@jdhoffa reviewing [the script as it was on May 3, 2023](https://github.com/RMI-PACTA/workflow.data.preparation/blob/bfd5fa606faeb72a6764a78b88f3e100f7936c0f/run_pacta_data_preparation.R) when this issue was created, it looks like the currencies and index_regions scraping was done in roughly the same place as [it is currently](https://github.com/RMI-PACTA/workflow.data.preparation/blob/06335ff933607a00140aee5c2074e05cb3c03157/run_pacta_data_preparation.R#L135-L149).

However, the sections that precede where/when the scraping is done seem reasonably appropriate/necessary to do before it, in my opinion.
```
# necessary packages -----------------------------------------------------------

# config -----------------------------------------------------------------------

# input filepaths --------------------------------------------------------------

# pre-flight filepaths ---------------------------------------------------------

# computed options -------------------------------------------------------------

# check that everything is ready to go -----------------------------------------
```

Do you remember what bits you'd prefer to do *after* the scraping?
